# Generated by Django 3.2.24 on 2024-03-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignworksup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='dailydetails_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='supervisor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('joindate', models.DateField()),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='worker_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='tosuprvsrcomplaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('SUPERVISOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.supervisor_table')),
                ('WORKEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.worker_table')),
            ],
        ),
        migrations.CreateModel(
            name='resources_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('SUPERVISOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.supervisor_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('RESOURCE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.resources_table')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.worker_table')),
            ],
        ),
        migrations.CreateModel(
            name='doubt_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.worker_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='ref_app.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='ref_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='assignworkworker_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ASSIGNWORK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.assignworksup_table')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.worker_table')),
            ],
        ),
        migrations.AddField(
            model_name='assignworksup_table',
            name='RESOURCE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.resources_table'),
        ),
        migrations.AddField(
            model_name='assignworksup_table',
            name='SUPERVISOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_app.supervisor_table'),
        ),
    ]
