# Generated by Django 3.2.24 on 2024-04-07 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignworksup_table',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignworkworker_table',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
