# Generated by Django 3.2.24 on 2024-04-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_app', '0002_auto_20240407_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='complaint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaint_table',
            name='reply',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tosuprvsrcomplaint_table',
            name='complaint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tosuprvsrcomplaint_table',
            name='reply',
            field=models.CharField(max_length=500),
        ),
    ]
